In [29]:
#Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix

import numpy as np
ar1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
ar1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
# Exercise 2: (Score : 1) Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. 

ar2=np.arange(1,20)
print(ar2)
result = ar2[4:15]
print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14 15]


In [31]:
#exercise 3: 
#(Score : 2) Create a Pandas series with the following data: 
#{'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.


import pandas as pd

s1=pd.Series({'apples':3,'bananas':2,'oranges':1})
s1


apples     3
bananas    2
oranges    1
dtype: int64

In [25]:

s1['pears']=4
s1

apples     3
bananas    2
oranges    1
pears      4
dtype: int64

In [49]:
#. Exercise 4: (Score : 2) Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data
s1=pd.DataFrame(np.array([["salvin",42,"Male"],["bimal",31,"Male"],["sisly",28,"Female"],["lilly",19,"Female"],["jordan",65,"Male"],["jane",33,"Female"],["sandra",25,"Female"],["rohit",22,"Male"],["julie",29,"Female"],["farhan",23,"Male"]]),index=["1","2","3","4","5","6","7","8","9","10"],columns=["name","age","gender"])
s1
s1

name age  gender
1   salvin  42    Male
2    bimal  31    Male
3    sisly  28  Female
4    lilly  19  Female
5   jordan  65    Male
6     jane  33  Female
7   sandra  25  Female
8    rohit  22    Male
9    julie  29  Female
10  farhan  23    Male

In [53]:
#Exercise 5: (Score : 1) Add a new column to the data frame created in question 1, called occupation. 
#The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe

s1['occupation']=[" Programmer","Analyst","Analyst","Manager","Programmer","Programmer","Programmer","Manager","Manager","Analyst"]
s1

name age  gender   occupation
1   salvin  42    Male   Programmer
2    bimal  31    Male      Analyst
3    sisly  28  Female      Analyst
4    lilly  19  Female      Manager
5   jordan  65    Male   Programmer
6     jane  33  Female   Programmer
7   sandra  25  Female   Programmer
8    rohit  22    Male      Manager
9    julie  29  Female      Manager
10  farhan  23    Male      Analyst

In [63]:
#Exercise 6: (Score : 1) Select the rows of the dataframe where the age is greater than or equal to 30. 
s1[s1['age']>='30']

name age  gender   occupation
1  salvin  42    Male   Programmer
2   bimal  31    Male      Analyst
5  jordan  65    Male   Programmer
6    jane  33  Female   Programmer

In [67]:
#Exercise 7: (Score : 2) Convert this dataframe to a csv file and read that csv file, finally display the contents.
s1.to_csv('people.csv',index=False)  
s1loaded = pd.read_csv('people.csv')
print(s1loaded)

     name  age  gender   occupation
0  salvin   42    Male   Programmer
1   bimal   31    Male      Analyst
2   sisly   28  Female      Analyst
3   lilly   19  Female      Manager
4  jordan   65    Male   Programmer
5    jane   33  Female   Programmer
6  sandra   25  Female   Programmer
7   rohit   22    Male      Manager
8   julie   29  Female      Manager
9  farhan   23    Male      Analyst
